/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CoffeeListItem: typeof import('./src/components/coffee-list-item.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
  }
}
